logging:
  level:
    guru: debug
server:
  port: 9092
spring:
  application:
    name: inventory-service
# defaults for docker image - vromero/activemq-artemis
  artemis:
    user: artemis
    password: simetraehcapa
  zipkin:
    enabled: false
  security:
    user:
      name: good
      password: bear