logging:
  level:
    guru: debug
server:
  port: 9092
spring:
# defaults for docker image - vromero/activemq-artemis
  artemis:
    host: 192.168.99.101
    user: artemis
    password: simetraehcapa
