logging:
  level:
    guru: debug
server:
  port: 9092
spring:
  application:
    name: inventory-service
# defaults for docker image - vromero/activemq-artemis
  artemis:
    host: 192.168.99.101
    user: artemis
    password: simetraehcapa
  zipkin:
    base-url: http://192.168.99.101:9411